export const ADD_FEATURED_PLAYLIST = 'ADD_FEATURED_PLAYLIST';
export const SELECTED_SONG = 'SELECTED_SONG';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const PLAYLIST_FORM = 'PLAYLIST_FORM';