export const ADD_FEATURED_PLAYLIST = 'ADD_FEATURED_PLAYLIST';
export const SELECTED_SONG = 'SELECTED_SONG';
export const CREATE_PLAYLIST = 'CREATE_PLAYLIST';
export const PLAYLIST_FORM = 'PLAYLIST_FORM';
export const DELETE_SONG = 'DELETE_SONG';
export const OPEN_MODAL = 'OPEN_MODAL';
export const CLOSE_MODAL = 'CLOSE_MODAL';